//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStorage
    {
        public int StorageID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
